name: CI

on:
  push:
    branches:
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Setup Go environment
      uses: actions/setup-go@v3.5.0
      with:
        go-version: 1.17

    - name: Change directory
      run: cd BidBay-Platform

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Test
      run: npm test
