name: CI

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: development

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Setup Go environment
      uses: actions/setup-go@v3.5.0
      with:
        go-version: 1.17.x

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Test
      run: npm test
